# Generated by Django 5.2.7 on 2025-11-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователь'},
        ),
    ]
