# Generated by Django 5.2.7 on 2025-11-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_image_alter_location_lat_alter_location_lng_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['id'], 'verbose_name': 'Обьяввление', 'verbose_name_plural': 'Обьявления'},
        ),
    ]
