# Generated by Django 5.2.7 on 2025-11-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_user_location_delete_location_delete_user'),
        ('users', '0003_remove_user_location_user_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Автор'),
        ),
    ]
