# Generated by Django 5.2.7 on 2025-11-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ad_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
    ]
